#!/bin/bash
#---------------------
# Testing cisco-plugin
#---------------------
set -e
apt-get -y install neutron-plugin-cisco

# update plugin path
sed -i 's/NEUTRON_PLUGIN_CONFIG\=.*/NEUTRON_PLUGIN_CONFIG\=\"\/etc\/neutron\/plugins\/cisco\/cisco_plugins\.ini\"/g' /etc/default/neutron-server
sed -i 's/core_plugin/core_plugin \= neutron\.plugins\.cisco\.network_plugin\.PluginV2/g' /etc/neutron/neutron.conf
service neutron-server restart > /dev/null 2>&1
if pidof -x neutron-server > /dev/null; then
    apt-get -y remove --purge neutron-plugin-cisco
    echo "OK"
else
    echo "ERROR: CISCO PLUGIN IS NOT RUNNING"
    apt-get -y remove --purge neutron-plugin-cisco
    exit 1
fi
