#!/bin/bash
#---------------------------
# Testing linuxbridge-plugin
#---------------------------
set -e
apt-get -y install neutron-plugin-linuxbridge

# update plugin path
sed -i 's/NEUTRON_PLUGIN_CONFIG\=.*/NEUTRON_PLUGIN_CONFIG\=\"\/etc\/neutron\/plugins\/linuxbridge\/linuxbridge_conf\.ini\"/g' /etc/default/neutron-server
sed -i 's/core_plugin/core_plugin \= neutron\.plugins\.linuxbridge\.lb_neutron_plugin\.LinuxBridgePluginV2/g' /etc/neutron/neutron.conf
service neutron-server restart  > /dev/null 2>&1
if pidof -x neutron-server > /dev/null; then
    apt-get -y remove --purge neutron-plugin-linuxbridge
    echo "OK"
else
    echo "ERROR: LINUXBRIDGE PLUGIN IS NOT RUNNING"
    apt-get -y remove --purge neutron-plugin-linuxbridge
    exit 1
fi
