#!/bin/bash
#-----------------------
# Testing midonet-plugin
#-----------------------
set -e
apt-get -y install neutron-plugin-midonet

# update plugin path
sed -i 's/NEUTRON_PLUGIN_CONFIG\=.*/NEUTRON_PLUGIN_CONFIG\=\"\/etc\/neutron\/plugins\/midonet\/midonet\.ini\"/g' /etc/default/neutron-server
sed -i 's/core_plugin/core_plugin \= neutron\.plugins\.midonet\.MidonetPluginV2/g' /etc/neutron/neutron.conf
service neutron-server restart  > /dev/null 2>&1
if pidof -x neutron-server > /dev/null; then
    apt-get -y remove --purge neutron-plugin-midonet
    echo "OK"
else
    echo "ERROR: MIDONET PLUGIN IS NOT RUNNING"
    apt-get -y remove --purge neutron-plugin-midonet
    exit 1
fi
