#!/bin/bash
#-------------------
# Testing nec-plugin
#-------------------
set -e
apt-get -y install neutron-plugin-nec

# update plugin path
sed -i 's/NEUTRON_PLUGIN_CONFIG\=.*/NEUTRON_PLUGIN_CONFIG\=\"\/etc\/neutron\/plugins\/nec\/nec\.ini\"/g' /etc/default/neutron-server
sed -i 's/core_plugin/core_plugin \= neutron\.plugins\.nec\.nec_plugin\.NECPluginV2/g' /etc/neutron/neutron.conf
service neutron-server restart  > /dev/null 2>&1
if pidof -x neutron-server > /dev/null; then
    apt-get -y remove --purge neutron-plugin-nec
    echo "OK"
else
    echo "ERROR: NEC PLUGIN IS NOT RUNNING"
    apt-get -y remove --purge neutron-plugin-nec
    exit 1
fi
