#!/bin/bash
#-------------------
# Testing ryu-plugin
#-------------------
set -e
apt-get -y install neutron-plugin-ryu

# update plugin path
sed -i 's/NEUTRON_PLUGIN_CONFIG\=.*/NEUTRON_PLUGIN_CONFIG\=\"\/etc\/neutron\/plugins\/ryu\/ryu\.ini\"/g' /etc/default/neutron-server
sed -i 's/core_plugin/core_plugin \= neutron\.plugins\.ryu\.ryu_neutron_plugin\.RyuNeutronPluginV2/g' /etc/neutron/neutron.conf
service neutron-server restart  > /dev/null 2>&1
if pidof -x neutron-server > /dev/null; then
    apt-get -y remove --purge neutron-plugin-ryu
    echo "OK"
else
    echo "ERROR: RYU PLUGIN IS NOT RUNNING"
    apt-get -y remove --purge neutron-plugin-ryu
    exit 1
fi
